# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'


Ingredient.create(name: "Achiote Seeds", aisle: "Spice")
Ingredient.create(name: "All Spice", aisle: "Spice", season: "autumn-winter", taste: "sweet", tips: "Add early in cooking.")
Ingredient.create(name: "Almond Butter", aisle: "Nut Butter", taste: "sweet")
Ingredient.create(name: "Almond Oil", aisle: "Oil", taste: "sweet")
Ingredient.create(name: "Almonds", aisle: "Nut", taste: "sweet")
Ingredient.create(name: "Anchovies", aisle: "Fish", taste: "salty")
Ingredient.create(name: "Anise, Star", aisle: "Spice", taste: "sweet, bitter", tips: "Add early in cooking process. Use in stir fries.")
Ingredient.create(name: "Apples", aisle: "Fruit", season: "autumn", taste: "sweet", techniques: "bake, caramelize, deep-fry, grill, poach, raw, saute, stew")
Ingredient.create(name: "Apricots, Dried", aisle: "Fruit", season: "summer", taste: "sweet", techniques: "poach, raw, stew")
Ingredient.create(name: "Apricots, Fresh", aisle: "Fruit", season: "summer", taste: "sweet", techniques: "bake, grill, poach, raw, stew")
Ingredient.create(name: "Artichokes", aisle: "Vegetable", season: "spring-early autumn", techniques: "bake, boil, braise, broil, deep-fry, grill, raw, roast, saute, steam, stew")
Ingredient.create(name: "Arugula", aisle: "Green", season: "spring-summer", taste: "bitter", techniques: "braise, raw (salads), saute, soups, wilt")
Ingredient.create(name: "Asparagus", aisle: "Vegetable", season: "spring", techniques: "blanch, boil, deep-fry, grill, pan roast, simmer, steam, stir-fry")
Ingredient.create(name: "Avocado Oil", aisle: "Oil")
Ingredient.create(name: "Avocados", aisle: "Fruit", season: "spring-summer", techniques: "raw", tips: "Use to add richness to a dish.")

Ingredient.create(name: "Bacon", aisle: "Meat", taste: "salty", techniques: "broil, roast, saute")
Ingredient.create(name: "Balsamic Vinegar", aisle: "Vinegar")
Ingredient.create(name: "Baking Soda", aisle: "Baking")
Ingredient.create(name: "Baking Powder", aisle: "Baking")
Ingredient.create(name: "Bananas", aisle: "Fruit", season: "winter", taste: "sweet, astringent", techniques: "bake, broil, caramelize, deep-fry, grill, poach, raw, saute", tips: "Sugar enhances the flavor of bananas.")
Ingredient.create(name: "Barley", aisle: "Grain", taste: "sweet, astringent", techniques: "simmer")
Ingredient.create(name: "Basil", aisle: "Herb", season: "summer", taste: "sweet", tips: "Add just before serving. Use to add a note of freshness to a dish.")
Ingredient.create(name: "Bass", aisle: "Fish", techniques: "bake, broil, deep-fry, poach, roast, saute, steam")
Ingredient.create(name: "Bass, Black", aisle: "Fish", techniques: "bake, broil, deep-fry, poach, roast, saute, steam")
Ingredient.create(name: "Bass, Sea", aisle: "Fish", season: "winter-spring", techniques: "bake, broil, deepfry, poach, roast, saute, steam")
Ingredient.create(name: "Bass, Striped", aisle: "Fish", techniques: "bake, braise, broil, deep-fry, grill, pan roast, poach, raw, roast, saute, sear, steam")
Ingredient.create(name: "Bay Leaf", aisle: "Herb", taste: "sweet, bitter", techniques: "can stand up to cooking (e.g., simmer, stew)")
Ingredient.create(name: "Beans", aisle: "Bean")
Ingredient.create(name: "Beans, Black", aisle: "Bean", techniques: "simmer")
Ingredient.create(name: "Beans, Broad", aisle: "Bean", season: "spring-summer", taste: "bitter", techniques: "boil, puree, simmer")
Ingredient.create(name: "Beans, Butter", aisle: "Bean")
Ingredient.create(name: "Beans, Cannellini", aisle: "Bean", season: "winter", techniques: "braise, puree, simmer")
Ingredient.create(name: "Beans, Fava", aisle: "Bean", season: "spring-summer", taste: "bitter", techniques: "boil, puree, simmer")
Ingredient.create(name: "Beans, Flageolet", aisle: "Bean", techniques: "simmer")
Ingredient.create(name: "Beans, Garbanzo", aisle: "Bean")
Ingredient.create(name: "Beans, Green", aisle: "Bean", season: "summer-autumn", techniques: "boil, grill, saute, steam, stir-fry")
Ingredient.create(name: "Beans, Kidney", aisle: "Bean", taste: "sweet-astringent", techniques: "boil, simmer")
Ingredient.create(name: "Beans, Lima", aisle: "Bean", season: "summer", taste: "bitter", techniques: "simmer, steam")
Ingredient.create(name: "Beans, Navy", aisle: "Bean", season: "winter", techniques: "simmer")
Ingredient.create(name: "Beans, Pinto", aisle: "Bean", season: "winter", techniques: "refry, simmer")
Ingredient.create(name: "Beans, Red", aisle: "Bean", techniques: "simmer")
Ingredient.create(name: "Beans, White", aisle: "Bean", season: "winter")
Ingredient.create(name: "Beef", aisle: "Meat", taste: "sweet", techniques: "see also individual cuts of beef", tips: "Clove adds richness to beef.")
Ingredient.create(name: "Beef - Brisket", aisle: "Meat", techniques: "barbecue, braise, corn, roast, simmer, smoke")
Ingredient.create(name: "Beef - Cheeks", aisle: "Meat", techniques: "braise")
Ingredient.create(name: "Beef - Kobe", aisle: "Meat")
Ingredient.create(name: "Beef - Loin", aisle: "Meat", techniques: "pan roast, roast")
Ingredient.create(name: "Beef - Oxtails", aisle: "Meat", techniques: "braise, stew")
Ingredient.create(name: "Beef - Ribs", aisle: "Meat", techniques: "barbecue, braise, (dry) roast")
Ingredient.create(name: "Beef - Roast", aisle: "Meat", techniques: "roast")
Ingredient.create(name: "Beef - Round", aisle: "Meat", techniques: "grill, saute, stir-fry")
Ingredient.create(name: "Beef - Shank", aisle: "Meat", techniques: "braise")
Ingredient.create(name: "Beef - Short Loin", aisle: "Meat")
Ingredient.create(name: "Beef - Short Ribs", aisle: "Meat", techniques: "barbecue, braise, stew")
Ingredient.create(name: "Beef - Steak", aisle: "Meat", techniques: "broil, grill, saute")
Ingredient.create(name: "Beef - Steak: Chuck", aisle: "Meat", techniques: "braise, grill, stew")
Ingredient.create(name: "Beef - Steak: Filet Mignon", aisle: "Meat", techniques: "broil, grill, saute")
Ingredient.create(name: "Beef - Steak: Flank", aisle: "Meat", techniques: "broil, grill, saute, stir-fry")
Ingredient.create(name: "Beef - Steak: Hanger", aisle: "Meat", techniques: "broil, grill, saute")
Ingredient.create(name: "Beef - Steak: Rib Eye", aisle: "Meat", techniques: "broil, grill, saute, stir-fry")
Ingredient.create(name: "Beef - Steak: Skirt", aisle: "Meat", techniques: "broil, grill, saute")
Ingredient.create(name: "Beef - Steak: Tartare", aisle: "Meat")
Ingredient.create(name: "Beer", aisle: "Alcohol", taste: "varies, from bitter to sweet")
Ingredient.create(name: "Beets", aisle: "Root Vegetable", season: "year round", taste: "sweet", techniques: "bake, boil, carpaccio, chips, roast, soup, steam")
Ingredient.create(name: "Bell Peppers", aisle: "Vegetable", season: "summer-autumn", taste: "bitter to sweet", techniques: "bake, broil, grill, roast, saute, steam, stew, stir-fry, stuff")
Ingredient.create(name: "Berries", aisle: "Berry", season: "spring-summer", techniques: "poach, raw")
Ingredient.create(name: "Blackberries", aisle: "Berry", season: "summer", taste: "sour", techniques: "cooked, raw")
Ingredient.create(name: "Black-eyed Peas", aisle: "Vegetable", techniques: "simmer")
Ingredient.create(name: "Black Pepper", aisle: "Spice")
Ingredient.create(name: "Blueberries", aisle: "Berry", season: "spring-summer", taste: "sour-sweet", techniques: "cooked, raw", tips: "Can substitute huckleberries.")
Ingredient.create(name: "Bluefish", aisle: "Fish", season: "spring-early autumn", techniques: "bake, blacken, braise, broil, grill, pan roast, poach, saute")
Ingredient.create(name: "Bok Choy", aisle: "Vegetable", season: "year round", taste: "bitter", techniques: "boil, braise, raw, stir-fry")
Ingredient.create(name: "Bonito Flakes, Dried", aisle: "Fish", taste: "salty", tips: "Use large flakes to make fish stock and small flakes to season dishes.")
Ingredient.create(name: "Bourbon", aisle: "Alcohol")
Ingredient.create(name: "Boysenberries", aisle: "Berry", season: "summer", taste: "sour-sweet")
Ingredient.create(name: "Broccoli", aisle: "Vegetable", season: "autumn-winter", techniques: "boil, deep-fry, saute, steam, stir-fry")
Ingredient.create(name: "Broccolini", aisle: "Vegetable", season: "year round", techniques: "blanch, raw, saute, steam, stir-fry")
Ingredient.create(name: "Broccoli Rabe", aisle: "Vegetable", season: "late fall-spring", taste: "bitter", techniques: "boil, saute, steam, stir-fry")
Ingredient.create(name: "Brussels Sprouts", aisle: "Vegetable", season: "autumn-winter", taste: "bitter", techniques: "boil, braise, saute, simmer, steam, stew, stir-fry")
Ingredient.create(name: "Bulgur Wheat", aisle: "Grain", techniques: "steam")
Ingredient.create(name: "Butter", aisle: "Dairy")
Ingredient.create(name: "Butter, Brown", aisle: "Dairy")
Ingredient.create(name: "Butter, Salted", aisle: "Dairy")
Ingredient.create(name: "Butter, Unsalted", aisle: "Dairy")
Ingredient.create(name: "Butter, Non-Dairy", aisle: "Non-Dairy")
Ingredient.create(name: "Buttermilk", aisle: "Dairy", taste: "sour")

Ingredient.create(name: "Cabbage", aisle: "Vegetable", season: "autumn-winter", techniques: "boil, braise, raw, saute, steam, stir-fry")
Ingredient.create(name: "Cabbage, Napa", aisle: "Vegetable", season: "year round", techniques: "bake, braise, grill, marinate, raw, saute, stew, stir-fry")
Ingredient.create(name: "Cabbage, Red", aisle: "Vegetable", season: "autumn-winter", techniques: "braise, marinate, raw")
Ingredient.create(name: "Cabbage, Savoy", aisle: "Vegetable", season: "autumn-winter", techniques: "boil, braise, raw, roast, steam")
Ingredient.create(name: "Cabernet Sauvignon", aisle: "Alcohol")
Ingredient.create(name: "Cantaloupe", aisle: "Fruit", season: "summer", taste: "sweet")
Ingredient.create(name: "Capers", aisle: "Pickle", taste: "salty, sour, pungent")
Ingredient.create(name: "Caraway Seeds", aisle: "Spice", taste: "sweet, sour", tips: "Add late in the cooking process.")
Ingredient.create(name: "Cardamom", aisle: "Spice", taste: "sweet, pungent", tips: "Add early when cooking.")
Ingredient.create(name: "Carrots", aisle: "Root Vegetable", season: "autumn-spring", techniques: "boil, braise, grill, raw, roast, saute, simmer, steam, stir-fry")
Ingredient.create(name: "Cashew Butter", aisle: "Nut Butter", taste: "sweet, rich")
Ingredient.create(name: "Cashews", aisle: "Nuts", taste: "sweet, rich")
Ingredient.create(name: "Catfish", aisle: "Fish", techniques: "broil, deep-fry, grill, poach, saute, steam, stir-fry")
Ingredient.create(name: "Cauliflower", aisle: "Vegetable", season: "autumn-winter", taste: "astringent", techniques: "boil, braise, deep-fry, gratin, puree, raw, roast, saute, simmer, steam")
Ingredient.create(name: "Cayenne Pepper", aisle: "Spice", taste: "piquant", tips: "Cayenne tastes hotter the more it cooks.")
Ingredient.create(name: "Celery", aisle: "Root Vegetable", season: "year round", taste: "astringent", techniques: "boil, braise, cream, gratine, raw, saute, steam, stir-fry")
Ingredient.create(name: "Celery Root", aisle: "Root Vegetable", season: "autumn-spring", techniques: "boil, deep-fry, raw, roast, steam", tips: "Always peel before using.")
Ingredient.create(name: "Celery Salt", aisle: "Spice")
Ingredient.create(name: "Celery Seed", aisle: "Spice", taste: "bitter, pungent")
Ingredient.create(name: "Chamomile", aisle: "Herb", taste: "sweet")
Ingredient.create(name: "Champagne", aisle: "Alcohol")
Ingredient.create(name: "Chard", aisle: "Green", season: "year round", taste: "bitter", techniques: "boil, braise, parboil, saute, steam, stir-fry")
Ingredient.create(name: "Chardonnay", aisle: "Alcohol")
Ingredient.create(name: "Cheese", aisle: "Dairy", taste: "sweet-sour")
Ingredient.create(name: "Cheese, Asiago", aisle: "Dairy")
Ingredient.create(name: "Cheese, Azeitao", aisle: "Dairy")
Ingredient.create(name: "Cheese, Blue", aisle: "Dairy")
Ingredient.create(name: "Cheese, Brie", aisle: "Dairy")
Ingredient.create(name: "Cheese, Burrata", aisle: "Dairy")
Ingredient.create(name: "Cheese, Cabrales", aisle: "Dairy")
Ingredient.create(name: "Cheese, Camembert", aisle: "Dairy")
Ingredient.create(name: "Cheese, Cheddar", aisle: "Dairy")
Ingredient.create(name: "Cheese, Colby", aisle: "Dairy")
Ingredient.create(name: "Cheese, Comte", aisle: "Dairy")
Ingredient.create(name: "Cheese, Cow's Milk", aisle: "Dairy")
Ingredient.create(name: "Cheese, Cream", aisle: "Dairy")
Ingredient.create(name: "Cheese, Emmental", aisle: "Dairy")
Ingredient.create(name: "Cheese, Epoisses", aisle: "Dairy")
Ingredient.create(name: "Cheese, Explorateur", aisle: "Dairy")
Ingredient.create(name: "Cheese, Feta", aisle: "Dairy")
Ingredient.create(name: "Cheese, Fontina", aisle: "Dairy")
Ingredient.create(name: "Cheese, Fromage Blanc", aisle: "Dairy")
Ingredient.create(name: "Cheese, Garrotxa", aisle: "Dairy")
Ingredient.create(name: "Cheese, Goat's Milk", aisle: "Dairy")
Ingredient.create(name: "Cheese, Goat - Fresh", aisle: "Dairy")
Ingredient.create(name: "Cheese, Gorgonzola", aisle: "Dairy")
Ingredient.create(name: "Cheese, Gouda", aisle: "Dairy")
Ingredient.create(name: "Cheese, Gruyere", aisle: "Dairy")
Ingredient.create(name: "Cheese, Hoja Santa", aisle: "Dairy")
Ingredient.create(name: "Cheese, Jack", aisle: "Dairy")
Ingredient.create(name: "Cheese, Mahon", aisle: "Dairy")
Ingredient.create(name: "Cheese, Manchego", aisle: "Dairy")
Ingredient.create(name: "Cheese, Mascarpone", aisle: "Dairy")
Ingredient.create(name: "Cheese, Monterey Jack", aisle: "Dairy")
Ingredient.create(name: "Cheese, Mozzarella", aisle: "Dairy")
Ingredient.create(name: "Cheese, Muenster", aisle: "Dairy")
Ingredient.create(name: "Cheese, Parmesan", aisle: "Dairy")
Ingredient.create(name: "Cheese, Pecorino", aisle: "Dairy")
Ingredient.create(name: "Cheese, Piave", aisle: "Dairy")
Ingredient.create(name: "Cheese, Reblochon", aisle: "Dairy")
Ingredient.create(name: "Cheese, Ricotta", aisle: "Dairy")
Ingredient.create(name: "Cheese, Roquefort", aisle: "Dairy")
Ingredient.create(name: "Cheese, Sheep's Milk", aisle: "Dairy")
Ingredient.create(name: "Cheese, Spanish", aisle: "Dairy")
Ingredient.create(name: "Cheese, Stilton", aisle: "Dairy")
Ingredient.create(name: "Cheese, Swiss", aisle: "Dairy")
Ingredient.create(name: "Cheese, Taleggio", aisle: "Dairy")
Ingredient.create(name: "Cheese, Triple Creme", aisle: "Dairy")
Ingredient.create(name: "Cheese, Vacherin", aisle: "Dairy")
Ingredient.create(name: "Cheese, Valdeon", aisle: "Dairy")
Ingredient.create(name: "Cheese, Vermont Shepherd", aisle: "Dairy")
Ingredient.create(name: "Cherries", aisle: "Fruit", season: "late spring-late summer", taste: "sweet", techniques: "flambe, poach, raw, stew")
Ingredient.create(name: "Chestnuts", aisle: "Nut", season: "autumn-winter", taste: "sweet", techniques: "boil, candy, grill, puree, raw, roast")
Ingredient.create(name: "Chicken", aisle: "Poultry", techniques: "bake, braise, broil, deep-fry, grill, poach, roast, saute, steam, stew, stir-fry")
Ingredient.create(name: "Chickpeas", aisle: "Bean", season: "summer", techniques: "simmer")
Ingredient.create(name: "Chicory", aisle: "Vegetable", season: "autumn-spring", techniques: "grill, raw")
Ingredient.create(name: "Chile Peppers", aisle: "Vegetable", season: "summer", taste: "hot", techniques: "raw, roast, saute", tips: "Add at the end of the cooking process. The spiciness of chile peppers suggests 'false heat.'")
Ingredient.create(name: "Chile Peppers, Anaheim", aisle: "Vegetable", taste: "hot, sweet")
Ingredient.create(name: "Chile Peppers, Ancho", aisle: "Vegetable", taste: "hot, sweet")
Ingredient.create(name: "Chile Peppers, Chipotle", aisle: "Vegetable", taste: "very hot, smoky")
Ingredient.create(name: "Chile Peppers, Guajillo", aisle: "Vegetable", taste: "hot")
Ingredient.create(name: "Chile Peppers, Habanero", aisle: "Vegetable", taste: "very hot, sweet")
Ingredient.create(name: "Chile Peppers, Jalepeno", aisle: "Vegetable", taste: "very hot")
Ingredient.create(name: "Chile Peppers, Pasilla", aisle: "Vegetable", taste: "hot")
Ingredient.create(name: "Chile Peppers, Piments D'Espelette", aisle: "Vegetable", taste: "hot")
Ingredient.create(name: "Chile Peppers, Poblano", aisle: "Vegetable", taste: "hot")
Ingredient.create(name: "Chile Peppers, Serrano", aisle: "Vegetable", taste: "very hot")
Ingredient.create(name: "Chili Paste", aisle: "Seasoning", taste: "hot")
Ingredient.create(name: "Chili Powder", aisle: "Spice", taste: "hot")
Ingredient.create(name: "Chinese Five-Spice Powder", aisle: "Spice")
Ingredient.create(name: "Chives", aisle: "Root Vegetable", season: "spring-autumn", tips: "Always use fresh, not cooked. Use in stir-fries.")
Ingredient.create(name: "Chocolate", aisle: "Baking", taste: "bitter-sweet (depending on sugar content)")
Ingredient.create(name: "Chocolate, White", aisle: "Baking")
Ingredient.create(name: "Chocolate, Dark", aisle: "Baking", taste: "bitter-sweet (depending on sugar content)")
Ingredient.create(name: "Chocolate, Milk", aisle: "Baking", taste: "bitter-sweet (depending on sugar content)")
Ingredient.create(name: "Chocolate, Vegan", aisle: "Baking", taste: "bitter-sweet (depending on sugar content)")
Ingredient.create(name: "Chorizo", aisle: "Meat", techniques: "saute, stew")
Ingredient.create(name: "Cilantro", aisle: "Herb", season: "spring-summer", taste: "sweer, sour", tips: "Always use fresh, not cooked - or if you must, add it at the very last minute.")
Ingredient.create(name: "Cinnamon", aisle: "Spice", season: "autumn-winter", taste: "sweet, bitter, pungent", tips: "Add early in cooking.")
Ingredient.create(name: "Citrus", aisle: "Fruit", season: "winter", taste: "sour")
Ingredient.create(name: "Clams", aisle: "Shellfish", season: "summer", taste: "salty", techniques: "bake, broil, deep-fry, grill, roast, saute, steam, stew")
Ingredient.create(name: "Cloves", aisle: "Spice", taste: "sweet, pungent", tips: "Add early in cooking.")
Ingredient.create(name: "Coconut", aisle: "Nut", season: "autumn-spring", taste: "sweet", techniques: "stir-fry")
Ingredient.create(name: "Coconut Milk", aisle: "Non-dairy")
Ingredient.create(name: "Cod", aisle: "Fish", techniques: "bake, boil, broil, cakes, deep-fry, fry, grill, poach, roast, saute, steam")
Ingredient.create(name: "Coffee", aisle: "Coffee", taste: "bitter")
Ingredient.create(name: "Cognac", aisle: "Alcohol")
Ingredient.create(name: "Collard Greens", aisle: "Green")
Ingredient.create(name: "Coriander", aisle: "Herb", taste: "sour, pungent, astringent", tips: "Add near the end of cooking. Toast coriander seeds to release their flavor.")
Ingredient.create(name: "Corn", aisle: "Vegetable", season: "summer", taste: "sweet", techniques: "boil, grill, roast, saute, steam")
Ingredient.create(name: "Corned Beef", aisle: "Meat")
Ingredient.create(name: "Cornish Game Hen", aisle: "Poultry")
Ingredient.create(name: "Couscous", aisle: "Pasta", techniques: "steep")
Ingredient.create(name: "Crab", aisle: "Shellfish", season: "summer", taste: "sweet", techniques: "bake, boil, broil, grill, steam")
Ingredient.create(name: "Cranberries", aisle: "Berry", season: "autumn-midwinter", taste: "sour", techniques: "boil")
Ingredient.create(name: "Crayfish", aisle: "Shellfish", season: "spring", techniques: "boil, broil, steam")
Ingredient.create(name: "Cream", aisle: "Dairy")
Ingredient.create(name: "Cream Cheese", aisle: "Dairy", taste: "sour")
Ingredient.create(name: "Cream, Sour", aisle: "Dairy")
Ingredient.create(name: "Creme Fraiche", aisle: "Dairy", taste: "sour")
Ingredient.create(name: "Cucumbers", aisle: "Root Vegetable", season: "spring-summer", taste: "sweet, astringent", techniques: "pickle, raw, salads, saute, soups")
Ingredient.create(name: "Cumin", aisle: "Spice", taste: "bitter, sweet", tips: "Add early in the cooking process. Toast cumin seeds in a dry pan to evaporate their moisture and increase their flavor.")
Ingredient.create(name: "Curry Leaves", aisle: "Herb", taste: "sour, bitter", tips: "Add later in cooking, or to finish the dish.")
Ingredient.create(name: "Curry Powder", aisle: "Spice", taste: "bittersweet, pungent", tips: "Add early in the cooking process.")

Ingredient.create(name: "Daikon", aisle: "Root Vegetable", season: "autumn-winter", taste: "sweet", techniques: "braise, marinate, raw, stew, stir-fry")
Ingredient.create(name: "Dandelion Greens", aisle: "Green")
Ingredient.create(name: "Dates", aisle: "Fruit", season: "autumn-winter", taste: "sweet")
Ingredient.create(name: "Dill", aisle: "Herb", season: "spring-autumn", taste: "sour, sweet", tips: "Always use fresh dill, not cooked.")
Ingredient.create(name: "Duck", aisle: "Poultry", season: "autumn", techniques: "braise, grill, roast, saute, stir-fry")

Ingredient.create(name: "Eggplant", aisle: "Root Vegetable", season: "summer", taste: "bitter", techniques: "bake, boil, braise, broil, deep-fry, grill, roast, saute, steam, stir-fry, stuff")
Ingredient.create(name: "Eggs", aisle: "Dairy", taste: "sweet, astringent", techniques: "bake, boil, fry, poach, scramble")
Ingredient.create(name: "Endive", aisle: "Vegetable", season: "winter-spring", taste: "bitter, sweet", techniques: "braise, glaze, grill, raw, roast")
Ingredient.create(name: "Escarole", aisle: "Green", season: "year round", taste: "bitter", techniques: "braise, grill, roast")

Ingredient.create(name: "Fennel", aisle: "Root Vegetable", season: "year round", taste: "sweet", techniques: "boil, braise, fry, grill, raw, roast, saute, steam")
Ingredient.create(name: "Fennel Seeds", aisle: "Spice", taste: "sweet", tips: "Add near end of cooking process.")
Ingredient.create(name: "Fenugreek", aisle: "Spice", season: "autumn", taste: "bitter, sweet")
Ingredient.create(name: "Flour", aisle: "Baking")
Ingredient.create(name: "Flour, All-Purpose", aisle: "Baking")
Ingredient.create(name: "Flour, Whole Wheat", aisle: "Baking")
Ingredient.create(name: "Flour, Gluten-Free", aisle: "Baking")
Ingredient.create(name: "Flour, Rye", aisle: "Baking")
Ingredient.create(name: "Feta Cheese", aisle: "Dairy")
Ingredient.create(name: "Figs, Dried", aisle: "Fruit", taste: "sweet", techniques: "stew")
Ingredient.create(name: "Figs, Fresh", aisle: "Fruit", season: "summer-autumn", taste: "sweet, astringent", techniques: "bake, broil, caramelize, deep-fry, grill, raw, roast")
Ingredient.create(name: "Filet Mignon", aisle: "Meat")
Ingredient.create(name: "Fish", aisle: "Fish", taste: "sweet")
Ingredient.create(name: "Fish Sauce", aisle: "Seasoning", taste: "salty")
Ingredient.create(name: "Five-Spice Powder", aisle: "Spice", taste: "sweet")
Ingredient.create(name: "Flounder", aisle: "Fish", season: "summer", techniques: "bake, broil, deep-fry, fry, poach, saute, steam, stir-fry")
Ingredient.create(name: "Fruit, Dried", aisle: "Fruit", taste: "sweet", tips: "If the fruit is hard, steam before using.")
Ingredient.create(name: "Fruit, Fresh", aisle: "Fruit", taste: "sweet", tips: "Sugar enhances the natural flavor of fruit.")
Ingredient.create(name: "Fruit, Tropical", aisle: "Fruit", taste: "sweet, sour")

Ingredient.create(name: "Game", aisle: "Meat", season: "autumn", techniques: "braise, roast", tips: "The flavor of cloves adds richness to game.")
Ingredient.create(name: "Garam Masala", aisle: "Spice", tips: "Add near the end of the cooking process or before serving.")
Ingredient.create(name: "Garlic", aisle: "Root Vegetable", season: "year round", techniques: "grill, raw, roast, saute")
Ingredient.create(name: "Gin", aisle: "Alcohol")
Ingredient.create(name: "Ginger", aisle: "Root Vegetable", season: "year round", taste: "sour, hot", techniques: "bake, stir-fry")
Ingredient.create(name: "Gringer, Ground", aisle: "Spice", taste: "pungent")
Ingredient.create(name: "Goat Cheese", aisle: "Dairy")
Ingredient.create(name: "Grapefruit", aisle: "Fruit", season: "year round", taste: "sour", techniques: "bake, boil, raw")
Ingredient.create(name: "Grapes", aisle: "Fruit", season: "summer-autumn", taste: "sweet")
Ingredient.create(name: "Grapes, Green", aisle: "Fruit")
Ingredient.create(name: "Grapes, Red", aisle: "Fruit")
Ingredient.create(name: "Green Beans", aisle: "Bean")
Ingredient.create(name: "Greens", aisle: "Green", season: "year round", taste: "bitter", techniques: "blanch, raw, saute, steam")
Ingredient.create(name: "Greens, Collard", aisle: "Green", season: "winter-spring", taste: "bitter", techniques: "boil, braise, steam, stir-fry")
Ingredient.create(name: "Greens, Dandelion", aisle: "Green", season: "late spring-early autumn", taste: "bitter", techniques: "raw, saute, steam")
Ingredient.create(name: "Greens, Kale", aisle: "Green")
Ingredient.create(name: "Greens, Mustard", aisle: "Green", season: "winter-spring", taste: "bitter", techniques: "boil, braise, grill, stew, wilt")
Ingredient.create(name: "Greens, Salad", aisle: "Green", season: "late spring")
Ingredient.create(name: "Greens, Turnip", aisle: "Green", season: "fall-winter", techniques: "boil, braise")
Ingredient.create(name: "Grits", aisle: "Grain", techniques: "simmer")
Ingredient.create(name: "Grouper", aisle: "Fish", season: "spring", techniques: "bake, braise, broil, deep-fry, grill, poach, roast, saute, steam, stir-fry")
Ingredient.create(name: "Guavas", aisle: "Fruit", season: "summer-autumn", taste: "sweet", techniques: "bake, juice, poach")

Ingredient.create(name: "Haddock", aisle: "Fish")
Ingredient.create(name: "Halibut", aisle: "Fish", season: "spring-summer", techniques: "bake, braise, broil, grill, pan roast, poach, roast, saute, steam")
Ingredient.create(name: "Ham", aisle: "Meat", taste: "salty", techniques: "bake, saute")
Ingredient.create(name: "Ham, Iberico", aisle: "Meat")
Ingredient.create(name: "Ham, Serrano", aisle: "Meat")
Ingredient.create(name: "Hazelnut Oil", aisle: "Oil")
Ingredient.create(name: "Hazelnuts", aisle: "Nut", taste: "sweet, salty")
Ingredient.create(name: "Herbes de Provence", aisle: "Herb")
Ingredient.create(name: "Herbs", aisle: "Herb")
Ingredient.create(name: "Honey", aisle: "Baking", taste: "sweet, astringent")
Ingredient.create(name: "Honeydew", aisle: "Fruit")
Ingredient.create(name: "Horseradish", aisle: "Root Vegetable", season: "spring-autumn", taste: "pungent, hot", tips: "Use horseradish raw or add at the end of the cooking process. Heat diminishes the pungency of horseradish.")

Ingredient.create(name: "Jicama", aisle: "Vegetable", season: "winter-spring", taste: "sweet", techniques: "cooked, raw")
Ingredient.create(name: "Juniper Berries", aisle: "Berry", season: "summer-autumn", taste: "bitter")

Ingredient.create(name: "Kale", aisle: "Green", season: "autumn-spring", taste: "bitter, sweet", techniques: "blanch, boil, braise, saute, steam, stir-fry")
Ingredient.create(name: "Kiwi Fruit", aisle: "Fruit", season: "late autumn-spring", taste: "sour", techniques: "raw")
Ingredient.create(name: "Kohlrabi", aisle: "Root Vegetable", season: "summer-autumn", techniques: "boil, steam, stir-fry")
Ingredient.create(name: "Kumquats", aisle: "Fruit", season: "autumn-winter", taste: "sour, bitter", techniques: "raw, stew")

Ingredient.create(name: "Lamb", aisle: "Meat", season: "spring", taste: "sweet, astringent", techniques: "braise, grill, roast, stew", tips: "Cloves add richness to the flavor of lamb.")
Ingredient.create(name: "Lamb, Chops", aisle: "Meat", techniques: "broil, grill, saute")
Ingredient.create(name: "Lavender", aisle: "Herb", taste: "sweet, sour", tips: "Caraway seeds can substitute for lavender.")
Ingredient.create(name: "Leeks", aisle: "Root Vegetable", season: "autumn-spring", taste: "sweet", techniques: "boil, braise, fry, grill, roast, steam", tips: "Add early in cooking process.")
Ingredient.create(name: "Legumes", aisle: "Bean")
Ingredient.create(name: "Lemons", aisle: "Fruit", season: "year round", taste: "sour")
Ingredient.create(name: "Lemons, Meyer", aisle: "Fruit", season: "autumn-spring", taste: "sour, sweet")
Ingredient.create(name: "Lemons, Preserved", aisle: "Fruit", taste: "sour")
Ingredient.create(name: "Lemon Basil", aisle: "Herb", taste: "sour")
Ingredient.create(name: "Lemongrass", aisle: "Herb", taste: "sour", tips: "Add near end of cooking process; use in stir-fries.")
Ingredient.create(name: "Lemon Verbena", aisle: "Herb", taste: "sour")
Ingredient.create(name: "Lentils", aisle: "Bean")
Ingredient.create(name: "Lettuce", aisle: "Green")
Ingredient.create(name: "Lettuce, Bibb", aisle: "Green")
Ingredient.create(name: "Lettuce - Bitter Greens", aisle: "Green")
Ingredient.create(name: "Lettuce - Chicories", aisle: "Green")
Ingredient.create(name: "Lettuce - Mesclun Greens", aisle: "Green")
Ingredient.create(name: "Lettuce - Romaine", aisle: "Green")
Ingredient.create(name: "Limes", aisle: "Fruit")
Ingredient.create(name: "Liver", aisle: "Meat")
Ingredient.create(name: "Liver, Calf's", aisle: "Meat")
Ingredient.create(name: "Liver, Chicken", aisle: "Poultry")
Ingredient.create(name: "Liver, Duck", aisle: "Poultry")
Ingredient.create(name: "Liver, Goose", aisle: "Poultry")
Ingredient.create(name: "Lobster", aisle: "Shellfish")
Ingredient.create(name: "Lotus Root", aisle: "Root Vegetable")
Ingredient.create(name: "Lychees", aisle: "Fruit")

Ingredient.create(name: "Macadamia Nut Oil", aisle: "Oil")
Ingredient.create(name: "Macadamia Nuts", aisle: "Nut")
Ingredient.create(name: "Mace", aisle: "Spice")
Ingredient.create(name: "Mackerel", aisle: "Fish")
Ingredient.create(name: "Mahi Mahi", aisle: "Fish")
Ingredient.create(name: "Mangoes", aisle: "Fruit")
Ingredient.create(name: "Maple Syrup", aisle: "Baking")
Ingredient.create(name: "Marjoram", aisle: "Herb")
Ingredient.create(name: "Mascarpone", aisle: "Dairy")
Ingredient.create(name: "Meats", aisle: "Meat")
Ingredient.create(name: "Melon", aisle: "Fruit")
Ingredient.create(name: "Merlot", aisle: "Alcohol")
Ingredient.create(name: "Mint", aisle: "Herb")
Ingredient.create(name: "Miso", aisle: "Seasoning")
Ingredient.create(name: "Molasses", aisle: "Baking")
Ingredient.create(name: "Monkfish", aisle: "Fish")
Ingredient.create(name: "Morels", aisle: "Vegetable")
Ingredient.create(name: "Mushrooms", aisle: "Vegetable")
Ingredient.create(name: "Mushrooms - Chanterelles", aisle: "Vegetable")
Ingredient.create(name: "Mushrooms - Cremini", aisle: "Vegetable")
Ingredient.create(name: "Mushrooms - Matsutake", aisle: "Vegetable")
Ingredient.create(name: "Mushrooms - Morels", aisle: "Vegetable")
Ingredient.create(name: "Mushrooms - Porcini", aisle: "Vegetable")
Ingredient.create(name: "Mushrooms - Cepes", aisle: "Vegetable")
Ingredient.create(name: "Mushrooms - King Bolete", aisle: "Vegetable")
Ingredient.create(name: "Mushrooms - Portobello", aisle: "Vegetable")
Ingredient.create(name: "Mushrooms - Shiitake", aisle: "Vegetable")
Ingredient.create(name: "Mussels", aisle: "Shellfish")
Ingredient.create(name: "Mustard", aisle: "Condiment")
Ingredient.create(name: "Mustard Greens", aisle: "Green")

Ingredient.create(name: "Nectarines", aisle: "Fruit")
Ingredient.create(name: "Nutmeg", aisle: "Spice")
Ingredient.create(name: "Nuts", aisle: "Nut")

Ingredient.create(name: "Oats", aisle: "Grain")
Ingredient.create(name: "Oatmeal", aisle: "Grain")
Ingredient.create(name: "Octopus", aisle: "Fish")
Ingredient.create(name: "Oil", aisle: "Oil")
Ingredient.create(name: "Oil, Almond", aisle: "Oil")
Ingredient.create(name: "Oil, Avocado", aisle: "Oil")
Ingredient.create(name: "Oil, Canola", aisle: "Oil")
Ingredient.create(name: "Oil, Grapeseed", aisle: "Oil")
Ingredient.create(name: "Oil, Hazelnut", aisle: "Oil")
Ingredient.create(name: "Oil, Macadamia Nut", aisle: "Oil")
Ingredient.create(name: "Oil, Olive", aisle: "Oil")
Ingredient.create(name: "Oil, Peanut", aisle: "Oil")
Ingredient.create(name: "Oil, Pecan", aisle: "Oil")
Ingredient.create(name: "Oil, Pistachio", aisle: "Oil")
Ingredient.create(name: "Oil, Porcini", aisle: "Oil")
Ingredient.create(name: "Oil, Pumpkin Seed", aisle: "Oil")
Ingredient.create(name: "Oil, Sesame", aisle: "Oil")
Ingredient.create(name: "Oil, Truffle", aisle: "Oil")
Ingredient.create(name: "Oil, Walnut", aisle: "Oil")
Ingredient.create(name: "Okra", aisle: "Vegetable")
Ingredient.create(name: "Onions", aisle: "Root Vegetable")
Ingredient.create(name: "Onions, Sweet", aisle: "Root Vegetable")
Ingredient.create(name: "Onions, White", aisle: "Root Vegetable")
Ingredient.create(name: "Onions, Red", aisle: "Root Vegetable")
Ingredient.create(name: "Onions, Yellow", aisle: "Root Vegetable")
Ingredient.create(name: "Onions, Green", aisle: "Root Vegetable")
Ingredient.create(name: "Oranges", aisle: "Fruit")
Ingredient.create(name: "Oranges, Blood", aisle: "Fruit")
Ingredient.create(name: "Oranges, Clementine", aisle: "Fruit")
Ingredient.create(name: "Oranges, Mandarin", aisle: "Fruit")
Ingredient.create(name: "Oregano", aisle: "Herb")
Ingredient.create(name: "Oxtails", aisle: "Meat")
Ingredient.create(name: "Oysters", aisle: "Shellfish")

Ingredient.create(name: "Pancetta", aisle: "Meat")
Ingredient.create(name: "Papayas", aisle: "Fruit")
Ingredient.create(name: "Paprika", aisle: "Spice")
Ingredient.create(name: "Paprika, Smoked", aisle: "Spice")
Ingredient.create(name: "Parsley", aisle: "Herb")
Ingredient.create(name: "Parsnips", aisle: "Root Vegetable")
Ingredient.create(name: "Passion Fruit", aisle: "Fruit")
Ingredient.create(name: "Pasta", aisle: "Grain")
Ingredient.create(name: "Peaches", aisle: "Fruit")
Ingredient.create(name: "Peanut Oil", aisle: "Oil")
Ingredient.create(name: "Peanuts", aisle: "Nut")
Ingredient.create(name: "Peanut Butter", aisle: "Nut Butter")
Ingredient.create(name: "Pears", aisle: "Fruit")
Ingredient.create(name: "Peas", aisle: "Vegetable")
Ingredient.create(name: "Pepper, Black", aisle: "Spice")
Ingredient.create(name: "Pepper, Green", aisle: "Vegetable")
Ingredient.create(name: "Pepper, Pink", aisle: "Vegetable")
Ingredient.create(name: "Pepper, Red", aisle: "Vegetable")
Ingredient.create(name: "Pepper, White", aisle: "Vegetable")
Ingredient.create(name: "Pepper, Bell", aisle: "Vegetable")
Ingredient.create(name: "Pepper, Chile", aisle: "Vegetable")
Ingredient.create(name: "Pepper, Peppadew", aisle: "Vegetable")
Ingredient.create(name: "Pepper, Piquillo", aisle: "Vegetable")
Ingredient.create(name: "Pepper, Spanish", aisle: "Vegetable")
Ingredient.create(name: "Persimmons", aisle: "Fruit")
Ingredient.create(name: "Pheasant", aisle: "Poultry")
Ingredient.create(name: "Pickles", aisle: "Pickle")
Ingredient.create(name: "Pimenton", aisle: "Spice")
Ingredient.create(name: "Pineapples", aisle: "Fruit")
Ingredient.create(name: "Pine Nuts", aisle: "Nut")
Ingredient.create(name: "Pinot Noir", aisle: "Alcohol")
Ingredient.create(name: "Pistachio Oil", aisle: "Oil")
Ingredient.create(name: "Pistachios", aisle: "Nut")
Ingredient.create(name: "Plantains, Green", aisle: "Fruit")
Ingredient.create(name: "Plantains, Sweet", aisle: "Fruit")
Ingredient.create(name: "Plums", aisle: "Fruit")
Ingredient.create(name: "Polenta", aisle: "Grain")
Ingredient.create(name: "Pomegranates", aisle: "Fruit")
Ingredient.create(name: "Pomegranate Molasses", aisle: "Baking")
Ingredient.create(name: "Pomelos", aisle: "Fruit")
Ingredient.create(name: "Ponzu Sauce", aisle: "Sauce")
Ingredient.create(name: "Poppy Seeds", aisle: "Seed")
Ingredient.create(name: "Pork", aisle: "Meat")
Ingredient.create(name: "Pork - Bacon", aisle: "Meat")
Ingredient.create(name: "Pork - Belly", aisle: "Meat")
Ingredient.create(name: "Pork - Chops", aisle: "Meat")
Ingredient.create(name: "Pork - Ham", aisle: "Meat")
Ingredient.create(name: "Pork - Loin", aisle: "Meat")
Ingredient.create(name: "Pork - Ribs", aisle: "Meat")
Ingredient.create(name: "Pork - Sausage", aisle: "Meat")
Ingredient.create(name: "Pork - Shoulder", aisle: "Meat")
Ingredient.create(name: "Pork - Tenderloin", aisle: "Meat")
Ingredient.create(name: "Potatoes", aisle: "Root Vegetable")
Ingredient.create(name: "Poultry", aisle: "Poultry")
Ingredient.create(name: "Proscuitto", aisle: "Meat")
Ingredient.create(name: "Prunes", aisle: "Fruit")
Ingredient.create(name: "Pumpkin", aisle: "Vegetable")
Ingredient.create(name: "Pumpkin Seeds", aisle: "Seed")

Ingredient.create(name: "Quail", aisle: "Poultry")
Ingredient.create(name: "Quince", aisle: "Fruit")

Ingredient.create(name: "Rabbit", aisle: "Meat")
Ingredient.create(name: "Radicchio", aisle: "Vegetable")
Ingredient.create(name: "Radishes", aisle: "Root Vegetable")
Ingredient.create(name: "Raisins", aisle: "Fruit")
Ingredient.create(name: "Ramps", aisle: "Root Vegetable")
Ingredient.create(name: "Raspberries", aisle: "Berry")
Ingredient.create(name: "Red Snapper", aisle: "Fish")
Ingredient.create(name: "Rhubarb", aisle: "Vegetable")
Ingredient.create(name: "Rice, White", aisle: "Grain")
Ingredient.create(name: "Rice, Arborio", aisle: "Grain")
Ingredient.create(name: "Rice, Risotto", aisle: "Grain")
Ingredient.create(name: "Rice, Basmati", aisle: "Grain")
Ingredient.create(name: "Rice, Jasmine", aisle: "Grain")
Ingredient.create(name: "Rice, Wild", aisle: "Grain")
Ingredient.create(name: "Rice, Brown", aisle: "Grain")
Ingredient.create(name: "Rice, Sushi", aisle: "Grain")
Ingredient.create(name: "Riesling", aisle: "Alcohol")
Ingredient.create(name: "Romaine", aisle: "Green")
Ingredient.create(name: "Rosemary", aisle: "Herb")
Ingredient.create(name: "Rum", aisle: "Alcohol")
Ingredient.create(name: "Rutabagas", aisle: "Root Vegetable")

Ingredient.create(name: "Saffron", aisle: "Spice")
Ingredient.create(name: "Sage", aisle: "Herb")
Ingredient.create(name: "Sake", aisle: "Alcohol")
Ingredient.create(name: "Salmon", aisle: "Fish")
Ingredient.create(name: "Salmon, Cured", aisle: "Fish")
Ingredient.create(name: "Salmon, Smoked", aisle: "Fish")
Ingredient.create(name: "Salt", aisle: "Seasoning")
Ingredient.create(name: "Salt, Fleur De Sel", aisle: "Seasoning")
Ingredient.create(name: "Salt, Hawaiian", aisle: "Seasoning")
Ingredient.create(name: "Salt, Japanese", aisle: "Seasoning")
Ingredient.create(name: "Salt, Kosher", aisle: "Seasoning")
Ingredient.create(name: "Salt, Maldon", aisle: "Seasoning")
Ingredient.create(name: "Salt, Sea - Coarse", aisle: "Seasoning")
Ingredient.create(name: "Salt, Sea - Fine", aisle: "Seasoning")
Ingredient.create(name: "Salt, Smoked", aisle: "Seasoning")
Ingredient.create(name: "Salt, Truffle", aisle: "Seasoning")
Ingredient.create(name: "Salt, Vanilla", aisle: "Seasoning")
Ingredient.create(name: "Sardines", aisle: "Fish")
Ingredient.create(name: "Saurerkraut", aisle: "Pickle")
Ingredient.create(name: "Sausages", aisle: "Meat")
Ingredient.create(name: "Sauvignon Blanc", aisle: "Alcohol")
Ingredient.create(name: "Scallions", aisle: "Root Vegetable")
Ingredient.create(name: "Scallops", aisle: "Shellfish")
Ingredient.create(name: "Scotch", aisle: "Alcohol")
Ingredient.create(name: "Sesame Seeds, Black", aisle: "Seed")
Ingredient.create(name: "Sesame Seeds, White", aisle: "Seed")
Ingredient.create(name: "Shallots", aisle: "Root Vegetable")
Ingredient.create(name: "Shellfish", aisle: "Shellfish")
Ingredient.create(name: "Shiitake Mushrooms", aisle: "Vegetable")
Ingredient.create(name: "Shiso Leaf", aisle: "Herb")
Ingredient.create(name: "Short Ribs", aisle: "Meat")
Ingredient.create(name: "Shrimp", aisle: "Shellfish")
Ingredient.create(name: "Skate", aisle: "Fish")
Ingredient.create(name: "Smoked Salmon", aisle: "Fish")
Ingredient.create(name: "Snap Peas", aisle: "Vegetable")
Ingredient.create(name: "Snapper", aisle: "Fish")
Ingredient.create(name: "Sole", aisle: "Fish")
Ingredient.create(name: "Sorrel", aisle: "Spice")
Ingredient.create(name: "Sour Cream", aisle: "Dairy")
Ingredient.create(name: "Soy Sauce", aisle: "Sauce")
Ingredient.create(name: "Spices", aisle: "Spice")
Ingredient.create(name: "Spinach", aisle: "Green")
Ingredient.create(name: "Sprouts", aisle: "Bean")
Ingredient.create(name: "Squab", aisle: "Poultry")
Ingredient.create(name: "Squash", aisle: "Vegetable")
Ingredient.create(name: "Squash, Acorn", aisle: "Vegetable")
Ingredient.create(name: "Squash, Butternut", aisle: "Vegetable")
Ingredient.create(name: "Squash, Kabocha", aisle: "Vegetable")
Ingredient.create(name: "Squash, Spaghetti", aisle: "Vegetable")
Ingredient.create(name: "Squash, Summer", aisle: "Vegetable")
Ingredient.create(name: "Squash, Winter", aisle: "Vegetable")
Ingredient.create(name: "Squash Blossoms", aisle: "Vegetable")
Ingredient.create(name: "Squid", aisle: "Fish")
Ingredient.create(name: "Star Anise", aisle: "Spice")
Ingredient.create(name: "Steak", aisle: "Meat")
Ingredient.create(name: "Strawberries", aisle: "Berry")
Ingredient.create(name: "Striped Bass", aisle: "Fish")
Ingredient.create(name: "Sugar", aisle: "Baking")
Ingredient.create(name: "Sugar, Light Brown", aisle: "Baking")
Ingredient.create(name: "Sugar, Dark Brown", aisle: "Baking")
Ingredient.create(name: "Sugar, Palm", aisle: "Baking")
Ingredient.create(name: "Sugar Snap Peas", aisle: "Vegetable")
Ingredient.create(name: "Sumac", aisle: "Spice")
Ingredient.create(name: "Sunchokes", aisle: "Vegetable")
Ingredient.create(name: "Sweetbreads", aisle: "Meat")
Ingredient.create(name: "Sweet Potatoes", aisle: "Root Vegetable")
Ingredient.create(name: "Swiss Chard", aisle: "Green")
Ingredient.create(name: "Swordfish", aisle: "Fish")
Ingredient.create(name: "Szechuan Pepper", aisle: "Spice")

Ingredient.create(name: "Tahini", aisle: "Nut Butter")
Ingredient.create(name: "Tamarind", aisle: "Fruit")
Ingredient.create(name: "Tangerines", aisle: "Fruit")
Ingredient.create(name: "Tarragon", aisle: "Herb")
Ingredient.create(name: "Tequila", aisle: "Alcohol")
Ingredient.create(name: "Thyme", aisle: "Herb")
Ingredient.create(name: "Tofu", aisle: "Meat-Substitute")
Ingredient.create(name: "Tomatillos", aisle: "Vegetable")
Ingredient.create(name: "Tomatoes", aisle: "Vegetable")
Ingredient.create(name: "Trout", aisle: "Fish")
Ingredient.create(name: "Trout, Smoked", aisle: "Fish")
Ingredient.create(name: "Truffles, Black", aisle: "Vegetable")
Ingredient.create(name: "Truffles, Pacific Northwest", aisle: "Vegetable")
Ingredient.create(name: "Tuna", aisle: "Fish")
Ingredient.create(name: "Turbot", aisle: "Fish")
Ingredient.create(name: "Turkey", aisle: "Poultry")
Ingredient.create(name: "Turmeric", aisle: "Spice")
Ingredient.create(name: "Turnip Greens", aisle: "Green")
Ingredient.create(name: "Turnips", aisle: "Root Vegetable")

Ingredient.create(name: "Vanilla", aisle: "Baking")
Ingredient.create(name: "Vanilla Extract", aisle: "Baking")
Ingredient.create(name: "Vanilla Pods", aisle: "Baking")
Ingredient.create(name: "Veal", aisle: "Meat")
Ingredient.create(name: "Veal - Breast", aisle: "Meat")
Ingredient.create(name: "Veal - Cheeks", aisle: "Meat")
Ingredient.create(name: "Veal - Chop", aisle: "Meat")
Ingredient.create(name: "Veal - Loin", aisle: "Meat")
Ingredient.create(name: "Veal - Shanks", aisle: "Meat")
Ingredient.create(name: "Veal - Tenderloin", aisle: "Meat")
Ingredient.create(name: "Vegetables", aisle: "Vegetable")
Ingredient.create(name: "Vegetables, Root", aisle: "Root Vegetables")
Ingredient.create(name: "Venison", aisle: "Meat")
Ingredient.create(name: "Verjus", aisle: "Alcohol")
Ingredient.create(name: "Vinegar", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Balsamic", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Banyuls", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Cabernet Sauvignon", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Champagne", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Chardonnay", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Cider", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Fruit", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Ice Wine", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Malt", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Red Wine", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Rice Wine", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Sherry", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Tarragon", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, Vincotto", aisle: "Vinegar")
Ingredient.create(name: "Vinegar, White Wine", aisle: "Vinegar")
Ingredient.create(name: "Vodka", aisle: "Alcohol")

Ingredient.create(name: "Walnut Oil", aisle: "Oil")
Ingredient.create(name: "Walnuts", aisle: "Nut")
Ingredient.create(name: "Wasabi", aisle: "Root Vegetable")
Ingredient.create(name: "Water Chestnuts", aisle: "Nut")
Ingredient.create(name: "Watercress", aisle: "Green")
Ingredient.create(name: "Watermelon", aisle: "Fruit")
Ingredient.create(name: "Whiskey", aisle: "Alcohol")
Ingredient.create(name: "Wild Rice", aisle: "Grain")
Ingredient.create(name: "Wine", aisle: "Alcohol")

Ingredient.create(name: "Yams", aisle: "Root Vegetable")
Ingredient.create(name: "Yeast", aisle: "Baking")
Ingredient.create(name: "Yogurt", aisle: "Dairy")
Ingredient.create(name: "Yogurt, Greek", aisle: "Dairy")
Ingredient.create(name: "Yogurt, Non-Dairy", aisle: "Non-Dairy")
Ingredient.create(name: "Yuzu Fruit", aisle: "Fruit")

Ingredient.create(name: "Zucchini", aisle: "Vegetable")
Ingredient.create(name: "Zucchini Blossoms", aisle: "Green")
Ingredient.create(name: "", aisle: "")
